### ISSUE TITLE
Output directory should have log rotate 

### ISSUE THREAD

**Issue by stalluri** [neptuneio/nagent#1]
Agent can abort becacause of disk issue, as we dont have control over output directory now.

Either 

1) We have logrotate on the output directory or
2) We remove stdout and stderr of an event, once we have a successfull publish to neptune's servers

**Comment by stalluri** [comment]
Alternatively, We can enforce deletion of stdout/stderr if more than 2-3MB on the agent side itself. This can help minimize output directory going out of proportion and also sending big files to neptune server

**Comment by buchireddy** [comment]
We now delete the stdout/stderr as soon as we read the output into memory and remove the files. Fix in 21bdd0d85eb2bafb8aa2e4a502f088a52872d6cb
