### ISSUE TITLE
Heartbeat errors on the agent

### ISSUE THREAD

**Issue by stalluri** [neptuneio/nagent#2]
![image](https://cloud.githubusercontent.com/assets/3118012/7396821/0d1b44b0-ee59-11e4-9f01-449d5df4d539.png)

**Comment by buchireddy** [comment]
Fixed the first error message already. I think the second error message is required and given that we are going to rely more on heartbeats, it makes sense to keep them.

@stalluri Is this good to be closed?

**Comment by stalluri** [comment]
Sounds good. Ship it.
