### ISSUE TITLE
Facing this no disk issue too many times.

### ISSUE THREAD

**Issue by stalluri** [neptuneio/nagent#3]
We are trying to write to our log file, and in case disk is full, we are exacerbating the problem by writing more.. I've see the below log error quite often. We need to handle this disk full issue gracefully.

![image](https://cloud.githubusercontent.com/assets/3118012/7439559/49807c76-f035-11e4-9e21-7f2af0195312.png)

**Comment by buchireddy** [comment]
We were unnecessarily updating the agent status file. I fixed this as part of 2809d5f1078c9d519ff4dda7618ce453940125d3
