### ISSUE TITLE
Assigned hostname not picked up

### ISSUE THREAD

**Issue by stalluri** [neptuneio/nagent#6]
![image](https://cloud.githubusercontent.com/assets/3118012/7446938/c30dba18-f19d-11e4-839d-5a2443c386c2.png)

**Comment by stalluri** [comment]
Secondly, registration is throwing several connection errors. I could confirm that curl to our staging endpoint goes through fine on the  machine

**Comment by buchireddy** [comment]
Can you run "hostname" and "hostname -f" commands on that host and see
what's the output?

Also, can you paste the contents of /etc/hosts?

On Sun, May 3, 2015 at 2:08 PM, stalluri <notifications@github.com> wrote:

> Secondly, registration is throwing several connection errors. I could
> confirm that curl to our staging endpoint goes through fine on the machine
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neptuneio/nagent/issues/6#issuecomment-98544443>.
>



-- 
Thanks,

- Buchi Reddy

**Comment by stalluri** [comment]
root@nodejs-app2:/home/neptuneioagent/neptuneio# hostname

nodejs-app2

root@nodejs-app2:/home/neptuneioagent/neptuneio# hostname -f

nodejs-app2.localdomain

**Comment by stalluri** [comment]
contents of /etc/hosts : 

# This file was generated by OpsWorks
# any manual changes will be removed on the next update.

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

# OpsWorks Layer State
127.0.0.1 localhost.localdomain localhost
127.0.1.1 nodejs-app2.localdomain nodejs-app2

10.0.0.11 nodejs-app2.localdomain nodejs-app2
52.0.91.204 nodejs-app2.localdomain-ext nodejs-app2-ext

**Comment by buchireddy** [comment]
The issue here was there were some spaces before the ASSIGNED_HOSTNAME keyword in the config file. Fixing them has helped.
